# -*- coding: utf-8 -*-
"""ASSIGNMENT2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kg4RMoUMOxJKIKG8svg5e6qDZbRl_kK9
"""

!git --version

!git config --global user.name "AWTT237"
!git config --global user.email "arnoldwilliam41@gmail.com"

!git config --list

token = "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"
username = "AWTT237"
repo_name = "ASSIGNMENT2"

# CLONE
!git clone https://{username}:{token}@github.com/{username}/{repo_name}

# Commented out IPython magic to ensure Python compatibility.
# %cd {repo_name}

# Commented out IPython magic to ensure Python compatibility.
# %ls

!git add --all

# Git and GitHub Assignment 2
# This notebook demonstrates basic Git operations.
def multiply_numbers(a, b):
    return a * b
print(multiply_numbers(3, 4))

!git commit -a -m "added file"

!git status

!git add README.md

! git remote -v

from google.colab import drive
drive.mount('/content/drive')

! git branch -m main

!git branch

!ls

!git add ASSIGNMENT2.ipynb
!git commit -m "Add ASSIGNMENT2 notebook"

!git push https://AWTT237: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@github.com/AWTT237/ASSIGNMENT2

